# libraries 
library(tidyverse)
library(lubridate)
library(broom)
library(nls.multstart) # devtools::install_github('padpadpadpad/nls.multstart')
library(nlstools)
library(scales)
library("devtools")
devtools::install_github("commfish/fngr")
library(fngr)
extrafont::font_import()
windowsFonts(Times=windowsFont("TT Times New Roman"))
theme_set(theme_report(base_size = 10))
library(MASS)
library(here)
library(magrittr)
library(bookdown)
devtools::install_github("tidyverse/purrr")
  